<?php

/**
 * BaseSetting
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $SiteName
 * @property string $homepage
 * @property string $sluzby
 * @property string $klienti
 * @property string $kontakt
 * @property string $animace
 * @property string $partneri
 * @property string $kon_form
 * @property string $zadej_pop
 * @property string $poptavka
 * @property string $odeslat
 * @property string $on_line_pop
 * @property string $mno_dal
 * @property string $email
 * @property string $tel
 * @property string $mobil
 * @property clob $pracovni_doba
 * @property string $ulice
 * @property string $mesto
 * @property string $stat
 * @property string $web_adr
 * @property string $ga_code
 * @property string $google_overeni
 * 
 * @method integer getId()             Returns the current record's "id" value
 * @method string  getSiteName()       Returns the current record's "SiteName" value
 * @method string  getHomepage()       Returns the current record's "homepage" value
 * @method string  getSluzby()         Returns the current record's "sluzby" value
 * @method string  getKlienti()        Returns the current record's "klienti" value
 * @method string  getKontakt()        Returns the current record's "kontakt" value
 * @method string  getAnimace()        Returns the current record's "animace" value
 * @method string  getPartneri()       Returns the current record's "partneri" value
 * @method string  getKonForm()        Returns the current record's "kon_form" value
 * @method string  getZadejPop()       Returns the current record's "zadej_pop" value
 * @method string  getPoptavka()       Returns the current record's "poptavka" value
 * @method string  getOdeslat()        Returns the current record's "odeslat" value
 * @method string  getOnLinePop()      Returns the current record's "on_line_pop" value
 * @method string  getMnoDal()         Returns the current record's "mno_dal" value
 * @method string  getEmail()          Returns the current record's "email" value
 * @method string  getTel()            Returns the current record's "tel" value
 * @method string  getMobil()          Returns the current record's "mobil" value
 * @method clob    getPracovniDoba()   Returns the current record's "pracovni_doba" value
 * @method string  getUlice()          Returns the current record's "ulice" value
 * @method string  getMesto()          Returns the current record's "mesto" value
 * @method string  getStat()           Returns the current record's "stat" value
 * @method string  getWebAdr()         Returns the current record's "web_adr" value
 * @method string  getGaCode()         Returns the current record's "ga_code" value
 * @method string  getGoogleOvereni()  Returns the current record's "google_overeni" value
 * @method Setting setId()             Sets the current record's "id" value
 * @method Setting setSiteName()       Sets the current record's "SiteName" value
 * @method Setting setHomepage()       Sets the current record's "homepage" value
 * @method Setting setSluzby()         Sets the current record's "sluzby" value
 * @method Setting setKlienti()        Sets the current record's "klienti" value
 * @method Setting setKontakt()        Sets the current record's "kontakt" value
 * @method Setting setAnimace()        Sets the current record's "animace" value
 * @method Setting setPartneri()       Sets the current record's "partneri" value
 * @method Setting setKonForm()        Sets the current record's "kon_form" value
 * @method Setting setZadejPop()       Sets the current record's "zadej_pop" value
 * @method Setting setPoptavka()       Sets the current record's "poptavka" value
 * @method Setting setOdeslat()        Sets the current record's "odeslat" value
 * @method Setting setOnLinePop()      Sets the current record's "on_line_pop" value
 * @method Setting setMnoDal()         Sets the current record's "mno_dal" value
 * @method Setting setEmail()          Sets the current record's "email" value
 * @method Setting setTel()            Sets the current record's "tel" value
 * @method Setting setMobil()          Sets the current record's "mobil" value
 * @method Setting setPracovniDoba()   Sets the current record's "pracovni_doba" value
 * @method Setting setUlice()          Sets the current record's "ulice" value
 * @method Setting setMesto()          Sets the current record's "mesto" value
 * @method Setting setStat()           Sets the current record's "stat" value
 * @method Setting setWebAdr()         Sets the current record's "web_adr" value
 * @method Setting setGaCode()         Sets the current record's "ga_code" value
 * @method Setting setGoogleOvereni()  Sets the current record's "google_overeni" value
 * 
 * @package    senzadubbio
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSetting extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('setting');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('SiteName', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('homepage', 'string', 15, array(
             'type' => 'string',
             'length' => 15,
             ));
        $this->hasColumn('sluzby', 'string', 15, array(
             'type' => 'string',
             'length' => 15,
             ));
        $this->hasColumn('klienti', 'string', 15, array(
             'type' => 'string',
             'length' => 15,
             ));
        $this->hasColumn('kontakt', 'string', 15, array(
             'type' => 'string',
             'length' => 15,
             ));
        $this->hasColumn('animace', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('partneri', 'string', 15, array(
             'type' => 'string',
             'length' => 15,
             ));
        $this->hasColumn('kon_form', 'string', 30, array(
             'type' => 'string',
             'length' => 30,
             ));
        $this->hasColumn('zadej_pop', 'string', 30, array(
             'type' => 'string',
             'length' => 30,
             ));
        $this->hasColumn('poptavka', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('odeslat', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('on_line_pop', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('mno_dal', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('email', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('tel', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('mobil', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('pracovni_doba', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('ulice', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('mesto', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('stat', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('web_adr', 'string', 55, array(
             'type' => 'string',
             'length' => 55,
             ));
        $this->hasColumn('ga_code', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('google_overeni', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'homepage',
              1 => 'sluzby',
              2 => 'klienti',
              3 => 'kontakt',
              4 => 'animace',
              5 => 'partneri',
              6 => 'kon_form',
              7 => 'zadej_pop',
              8 => 'poptavka',
              9 => 'odeslat',
              10 => 'on_line_pop',
              11 => 'mno_dal',
              12 => 'mobil',
              13 => 'ulice',
              14 => 'mesto',
              15 => 'tel',
              16 => 'email',
              17 => 'stat',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($i18n0);
    }
}