<?php

/**
 * BaseKlienti
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $slug
 * @property string $title
 * @property boolean $publikovat
 * @property clob $popis
 * @property string $img_gray
 * @property string $img_hover
 * @property string $url
 * 
 * @method integer getId()         Returns the current record's "id" value
 * @method string  getName()       Returns the current record's "name" value
 * @method string  getSlug()       Returns the current record's "slug" value
 * @method string  getTitle()      Returns the current record's "title" value
 * @method boolean getPublikovat() Returns the current record's "publikovat" value
 * @method clob    getPopis()      Returns the current record's "popis" value
 * @method string  getImgGray()    Returns the current record's "img_gray" value
 * @method string  getImgHover()   Returns the current record's "img_hover" value
 * @method string  getUrl()        Returns the current record's "url" value
 * @method Klienti setId()         Sets the current record's "id" value
 * @method Klienti setName()       Sets the current record's "name" value
 * @method Klienti setSlug()       Sets the current record's "slug" value
 * @method Klienti setTitle()      Sets the current record's "title" value
 * @method Klienti setPublikovat() Sets the current record's "publikovat" value
 * @method Klienti setPopis()      Sets the current record's "popis" value
 * @method Klienti setImgGray()    Sets the current record's "img_gray" value
 * @method Klienti setImgHover()   Sets the current record's "img_hover" value
 * @method Klienti setUrl()        Sets the current record's "url" value
 * 
 * @package    senzadubbio
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseKlienti extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('klienti');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('slug', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('title', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('publikovat', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('popis', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('img_gray', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('img_hover', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'title',
              1 => 'popis',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($i18n0);
    }
}