<?php

/**
 * BaseStranky
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $slug
 * @property string $title
 * @property string $str_title
 * @property boolean $publikovat
 * @property clob $perex
 * @property integer $gallery_id
 * @property integer; $prezentace_id
 * @property clob $popis
 * @property string $keywords
 * @property string $description
 * @property Gallery $Gallery
 * 
 * @method integer getId()          Returns the current record's "id" value
 * @method string  getName()        Returns the current record's "name" value
 * @method string  getSlug()        Returns the current record's "slug" value
 * @method string  getTitle()       Returns the current record's "title" value
 * @method string  getStrTitle()    Returns the current record's "str_title" value
 * @method boolean getPublikovat()  Returns the current record's "publikovat" value
 * @method clob    getPerex()       Returns the current record's "perex" value
 * @method integer getGalleryId()   Returns the current record's "gallery_id" value
 * @method clob    getPopis()       Returns the current record's "popis" value
 * @method string  getKeywords()    Returns the current record's "keywords" value
 * @method string  getDescription() Returns the current record's "description" value
 * @method Gallery getGallery()     Returns the current record's "Gallery" value
 * @method Stranky setId()          Sets the current record's "id" value
 * @method Stranky setName()        Sets the current record's "name" value
 * @method Stranky setSlug()        Sets the current record's "slug" value
 * @method Stranky setTitle()       Sets the current record's "title" value
 * @method Stranky setStrTitle()    Sets the current record's "str_title" value
 * @method Stranky setPublikovat()  Sets the current record's "publikovat" value
 * @method Stranky setPerex()       Sets the current record's "perex" value
 * @method Stranky setGalleryId()   Sets the current record's "gallery_id" value
 * @method Stranky setPopis()       Sets the current record's "popis" value
 * @method Stranky setKeywords()    Sets the current record's "keywords" value
 * @method Stranky setDescription() Sets the current record's "description" value
 * @method Stranky setGallery()     Sets the current record's "Gallery" value
 * 
 * @package    senzadubbio
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStranky extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('stranky');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('slug', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('title', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('str_title', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('publikovat', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('perex', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('gallery_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('prezentace_id', 'integer;', null, array(
             'type' => 'integer;',
             ));
        $this->hasColumn('popis', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('keywords', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Gallery', array(
             'local' => 'prezentace_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'title',
              1 => 'str_title',
              2 => 'perex',
              3 => 'popis',
              4 => 'keywords',
              5 => 'description',
              6 => 'prezentace_id',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($i18n0);
    }
}