<?php

/**
 * BaseKategorie
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property clob $popis
 * @property integer $poradi
 * @property Doctrine_Collection $Stranky
 * @property Doctrine_Collection $Odkazy
 * 
 * @method integer             getId()      Returns the current record's "id" value
 * @method string              getName()    Returns the current record's "name" value
 * @method clob                getPopis()   Returns the current record's "popis" value
 * @method integer             getPoradi()  Returns the current record's "poradi" value
 * @method Doctrine_Collection getStranky() Returns the current record's "Stranky" collection
 * @method Doctrine_Collection getOdkazy()  Returns the current record's "Odkazy" collection
 * @method Kategorie           setId()      Sets the current record's "id" value
 * @method Kategorie           setName()    Sets the current record's "name" value
 * @method Kategorie           setPopis()   Sets the current record's "popis" value
 * @method Kategorie           setPoradi()  Sets the current record's "poradi" value
 * @method Kategorie           setStranky() Sets the current record's "Stranky" collection
 * @method Kategorie           setOdkazy()  Sets the current record's "Odkazy" collection
 * 
 * @package    senzadubbio
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseKategorie extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('kategorie');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('popis', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('poradi', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Stranky', array(
             'local' => 'id',
             'foreign' => 'kategorie_id'));

        $this->hasMany('Odkazy', array(
             'local' => 'id',
             'foreign' => 'kategorie_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'name',
             ),
             'canUpdate' => true,
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}