<?php

/**
 * BaseSluzby
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $info_list
 * @property string $name
 * @property string $title
 * @property clob $popis
 * 
 * @method integer getId()        Returns the current record's "id" value
 * @method string  getInfoList()  Returns the current record's "info_list" value
 * @method string  getName()      Returns the current record's "name" value
 * @method string  getTitle()     Returns the current record's "title" value
 * @method clob    getPopis()     Returns the current record's "popis" value
 * @method Sluzby  setId()        Sets the current record's "id" value
 * @method Sluzby  setInfoList()  Sets the current record's "info_list" value
 * @method Sluzby  setName()      Sets the current record's "name" value
 * @method Sluzby  setTitle()     Sets the current record's "title" value
 * @method Sluzby  setPopis()     Sets the current record's "popis" value
 * 
 * @package    senzadubbio
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSluzby extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sluzby');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('info_list', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('popis', 'clob', null, array(
             'type' => 'clob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'title',
              1 => 'popis',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($i18n0);
    }
}