# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  .settings:
    no_script_name:         false
    logging_enabled:        false
    compressed:             true
    cache:                  false

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false
    compressed:             true
    cache:                  false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:
  .settings:
    # Form security secret (CSRF protection)
    csrf_secret:            5b0f2bb805cc49cascad1cDASaDAAaSsdd05d9535683e8bb92f4d

    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_RAW

    # Enable the database manager
    use_database:           true
    default_culture:        cs_CZ
    culture:                cs
    i18n:                   on
    
    enabled_modules:      [ i18n, default, sfGuardGroup, sfGuardUser, sfGuardPermission, sfMediaBrowser, sfGuardAuth ]

    # enable tinymce wysiwyg editor
    rich_text_js_dir:       js/tiny_mce

    login_module:           sfGuardAuth
    login_action:           signin

    secure_module:          sfGuardAuth
    secure_action:          secure