generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sluzby
    theme:                 jroller
    non_verbose_templates: true
    with_show:             true
    singular:              ~
    plural:                ~
    route_prefix:          sluzby
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        name:  
          label: Název služby pro odkaz
        title:  
          label: Název služby
        popis:  
          label: Popis služby
        slug:
          label: adresa odkazu HTML          
      list:    
        display: [info_list, name]
      filter:  
        display: [info_list, name]
      form:    ~
      edit:    
        display: 
          Základni data: [info_list]          
          "Česky": [cs]
          Anglicky: [en]
          Německy : [de]
          Italsky: [it]        
      new:     ~
