<?php

/**
 * OdkazyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OdkazyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OdkazyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Odkazy');
    }
}