<?php

/**
 * SluzbyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SluzbyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SluzbyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Sluzby');
    }
}