<?php

/**
 * StrankyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StrankyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StrankyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Stranky');
    }
    
    static public function getLuceneIndex()
    {
        ProjectConfiguration::registerZend();

        if (file_exists($index = self::getLuceneIndexFile()))
        {
            return Zend_Search_Lucene::open($index);
        }

        return Zend_Search_Lucene::create($index);
    }

    static public function getLuceneIndexFile()
    {
        return sfConfig::get('sf_data_dir') . '/item.' . sfConfig::get('sf_environment') . '.index';
    }

    public function getForLuceneQuery($query, $options = array())
    {
        $hits = self::getLuceneIndex()->find($query);

        $pks = array();
        foreach ($hits as $hit)
        {
            $pks[] = $hit->pk;
        }

        if (empty($pks))
        {
            return Doctrine_Query::create()
                    ->from('Stranky z')
                    ->where('FALSE');
        }

        $q = Doctrine_Query::create()
                        ->from('Stranky z')
                        ->leftjoin('z.Kategorie k')
                        ->where('z.publikovat = 1')
                        ->whereIn('z.id', $pks)
                        ->orderBy('z.id desc');

        return $q;
    }
    
}