generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Gallery
    theme:                 jroller
    non_verbose_templates: true
    with_show:             true
    singular:              ~
    plural:                ~
    route_prefix:          gallery
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        is_active:
          label: Aktivní
        title:
          label: Titulek
        description:
          label: Popis
        kat:
          label: Skupina kategorie zájezdu
          help: Označení do které skupiny daný záznam patří. Leto, Zima, Agroturistika. Nutno pro rozdeleni pro microsite a aplikaci ceniků
        slug:
          label: adresa odkazu HTML
      list:
        display: [=title, is_active, description, slug]
        title: Galerie
      filter:  
        display: []
      form:
        display: [title, description ,image, ~showGalleryImages]
      edit:
        title: Editace galerie
      new:
        title: Nová galerie


