<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/01/29 20:29:03

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=senzadubbio',
  'username' => 'root',
  'password' => 'SQLserverAT',
  'attributes' => 
  array (
    'default_table_collate' => 'utf8_czech_ci',
    'default_table_charset' => 'utf8',
  ),
  'name' => 'doctrine',
)),);
